# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(614, 492)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 595, 341))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.sum = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.sum.setText("")
        self.sum.setObjectName("sum")
        self.gridLayout.addWidget(self.sum, 2, 3, 1, 2)
        self.foodName = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.foodName.setInputMask("")
        self.foodName.setObjectName("foodName")
        self.gridLayout.addWidget(self.foodName, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setStyleSheet("font-style: italic;\n"
"color: green;")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.add = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.add.setStyleSheet("font-weight: bold;\n"
"background-color: rgb(0, 255, 0);")
        self.add.setObjectName("add")
        self.gridLayout.addWidget(self.add, 0, 4, 1, 1)
        self.men = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.men.setObjectName("men")
        self.gridLayout.addWidget(self.men, 7, 0, 1, 2)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setStyleSheet("font-style: italic;\n"
"color: green;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 5)
        self.caloriesNumber = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.caloriesNumber.setStyleSheet("")
        self.caloriesNumber.setInputMask("")
        self.caloriesNumber.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.caloriesNumber.setObjectName("caloriesNumber")
        self.gridLayout.addWidget(self.caloriesNumber, 0, 3, 1, 1)
        self.image = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.image.setMaximumSize(QtCore.QSize(16777215, 200))
        self.image.setText("")
        self.image.setObjectName("image")
        self.gridLayout.addWidget(self.image, 5, 0, 1, 5)
        self.sumColor = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.sumColor.setStyleSheet("background-color: green;\n"
"color: white;")
        self.sumColor.setObjectName("sumColor")
        self.gridLayout.addWidget(self.sumColor, 2, 0, 1, 3)
        self.woman = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.woman.setObjectName("woman")
        self.gridLayout.addWidget(self.woman, 7, 2, 1, 3)
        self.foodList = QtWidgets.QListWidget(parent=self.gridLayoutWidget)
        self.foodList.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.foodList.setDragEnabled(False)
        self.foodList.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.foodList.setObjectName("foodList")
        self.gridLayout.addWidget(self.foodList, 1, 0, 1, 5)
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 360, 591, 111))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.small = QtWidgets.QRadioButton(parent=self.groupBox)
        self.small.setGeometry(QtCore.QRect(10, 10, 431, 20))
        self.small.setObjectName("small")
        self.average = QtWidgets.QRadioButton(parent=self.groupBox)
        self.average.setGeometry(QtCore.QRect(10, 40, 441, 20))
        self.average.setObjectName("average")
        self.big = QtWidgets.QRadioButton(parent=self.groupBox)
        self.big.setGeometry(QtCore.QRect(10, 70, 431, 20))
        self.big.setObjectName("big")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Kalkulator kalorii"))
        self.label_2.setText(_translate("Dialog", "Liczba kalorii:"))
        self.add.setText(_translate("Dialog", "Dodaj"))
        self.men.setText(_translate("Dialog", "Mężczyzna"))
        self.label.setText(_translate("Dialog", "Nazwa posiłku:"))
        self.label_6.setText(_translate("Dialog", "-------------------------------------------------------------------------------------------------"))
        self.sumColor.setText(_translate("Dialog", "Suma sporzytych kalorii:"))
        self.woman.setText(_translate("Dialog", "Kobieta"))
        self.small.setText(_translate("Dialog", "Mała aktywność fizyczna"))
        self.average.setText(_translate("Dialog", "Średnia aktywność fizyczna"))
        self.big.setText(_translate("Dialog", "Duża aktywnośc fizyczna"))
